In [3]:
import numpy as np

In [4]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
n1

array([1, 2, 3, 4])

In [6]:
x=[]
len(dir(x))

47

In [7]:
len(dir(n1))

165

In [8]:
n1.shape

(4,)

In [9]:
n2 = np.array([[1,2,3],[2,3,4]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeros   

In [10]:
# in normal range we can not write . values but in arange we can
x=np.arange(-10,10,.2)
x.shape

(100,)

In [11]:
y= np.linspace(1,5,25)#it is enclusive type
print(y)
y.shape

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


(25,)

In [12]:
np.random.rand(3,3)

array([[0.23800458, 0.65632131, 0.29782878],
       [0.86538549, 0.51185198, 0.90341873],
       [0.89093402, 0.55938841, 0.14658794]])

In [13]:
np.random.randn(10)

array([ 0.1689691 ,  0.07649411,  1.78034213, -1.62492592, -1.34405354,
       -0.67313662, -0.40121477, -1.15269303, -1.11404507,  0.31020165])

In [14]:
np.random.randint(1,5,(5,5))

array([[2, 3, 4, 4, 4],
       [4, 3, 1, 2, 2],
       [1, 2, 4, 3, 1],
       [2, 4, 1, 4, 3],
       [3, 1, 4, 2, 2]])

In [15]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[8 1]
 [7 2]
 [8 7]]
[[4 5]
 [8 2]
 [9 3]]


In [16]:
x+5

array([[13,  6],
       [12,  7],
       [13, 12]])

In [17]:
x*5

array([[40,  5],
       [35, 10],
       [40, 35]])

In [18]:
x+y # matrix addition

array([[12,  6],
       [15,  4],
       [17, 10]])

In [19]:
x*y

array([[32,  5],
       [56,  4],
       [72, 21]])

In [20]:
x.T

array([[8, 7, 8],
       [1, 2, 7]])

In [21]:
x.dot(y.T)

array([[37, 66, 75],
       [38, 60, 69],
       [67, 78, 93]])

In [22]:
np.sin(x)

array([[0.98935825, 0.84147098],
       [0.6569866 , 0.90929743],
       [0.98935825, 0.6569866 ]])

In [23]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())

33
5.5
2.8722813232690143
1
8


In [26]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)
print(a2.shape)


(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [27]:
a2.reshape(50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [28]:
m=np.random.randint(1,10,(10,10))
print(m)

[[1 1 4 8 8 4 2 4 9 5]
 [3 1 2 7 8 6 2 7 5 1]
 [7 2 6 6 1 1 3 1 3 8]
 [7 9 7 7 5 4 3 7 5 4]
 [7 1 3 2 4 6 4 4 3 3]
 [2 3 3 1 5 3 7 7 9 6]
 [2 5 7 4 3 9 9 8 1 7]
 [6 9 5 9 2 6 2 2 1 3]
 [6 8 1 8 4 6 2 8 8 1]
 [2 3 5 6 6 1 3 1 5 9]]


In [30]:
print(m[0, 0]) #first row , first coloumn
print(m[0, -1])# first row last colomn
print(m[-1,0])# last row first coloummn
print(m[-1, -1])# last row last coloumn

1
5
2
9


In [31]:
print(m[0]) #first row
print(m[1]) #second row
print(m[-1]) # last row
print(m[:3]) # first 3 rows
print(m[-3:]) #last 3 rows

[1 1 4 8 8 4 2 4 9 5]
[3 1 2 7 8 6 2 7 5 1]
[2 3 5 6 6 1 3 1 5 9]
[[1 1 4 8 8 4 2 4 9 5]
 [3 1 2 7 8 6 2 7 5 1]
 [7 2 6 6 1 1 3 1 3 8]]
[[6 9 5 9 2 6 2 2 1 3]
 [6 8 1 8 4 6 2 8 8 1]
 [2 3 5 6 6 1 3 1 5 9]]


In [33]:
print(m[:0])# first coloumn
print(m[:,-1]) #last coloumn
print(m[:,-3:])# last 3 coloumn

[]
[5 1 8 4 3 6 7 3 1 9]
[[4 9 5]
 [7 5 1]
 [1 3 8]
 [7 5 4]
 [4 3 3]
 [7 9 6]
 [8 1 7]
 [2 1 3]
 [8 8 1]
 [1 5 9]]


In [34]:
print(m[:, [0,2,3,5]])

[[1 4 8 4]
 [3 2 7 6]
 [7 6 6 1]
 [7 7 7 4]
 [7 3 2 6]
 [2 3 1 3]
 [2 7 4 9]
 [6 5 9 6]
 [6 1 8 6]
 [2 5 6 1]]


In [36]:
#filtering
m<5 #BOOLEAN filter

array([[ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [ True,  True,  True, False, False, False,  True, False, False,
         True],
       [False,  True, False, False,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False,  True,  True, False, False,
         True],
       [False,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True, False, False, False,
        False],
       [ True, False, False,  True,  True, False, False, False,  True,
        False],
       [False, False, False, False,  True, False,  True,  True,  True,
         True],
       [False, False,  True, False,  True, False,  True, False, False,
         True],
       [ True,  True, False, False, False,  True,  True,  True, False,
        False]])

In [37]:
m[m<5]

array([1, 1, 4, 4, 2, 4, 3, 1, 2, 2, 1, 2, 1, 1, 3, 1, 3, 4, 3, 4, 1, 3,
       2, 4, 4, 4, 3, 3, 2, 3, 3, 1, 3, 2, 4, 3, 1, 2, 2, 2, 1, 3, 1, 4,
       2, 1, 2, 3, 1, 3, 1])

In [38]:
m[m>5]

array([8, 8, 9, 7, 8, 6, 7, 7, 6, 6, 8, 7, 9, 7, 7, 7, 7, 6, 7, 7, 9, 6,
       7, 9, 9, 8, 7, 6, 9, 9, 6, 6, 8, 8, 6, 8, 8, 6, 6, 9])

In [39]:
m[(m>3) & (m<=6)]

array([4, 4, 4, 5, 6, 5, 6, 6, 5, 4, 5, 4, 4, 6, 4, 4, 5, 6, 5, 4, 6, 5,
       6, 6, 4, 6, 5, 6, 6, 5])

In [40]:
open?

Signature:
open(
    file,
    mode='r',
    buffering=-1,
    encoding=None,
    errors=None,
    newline=None,
    closefd=True,
    opener=None,
)
Docstring:
Open file and return a stream.  Raise OSError upon failure.

file is either a text or byte string giving the name (and the path
if the file isn't in the current working directory) of the file to
be opened or an integer file descriptor of the file to be
wrapped. (If a file descriptor is given, it is closed when the
returned I/O object is closed, unless closefd is set to False.)

mode is an optional string that specifies the mode in which the file
is opened. It defaults to 'r' which means open for reading in text
mode.  Other common values are 'w' for writing (truncating the file if
it already exists), 'x' for creating and writing to a new file, and
'a' for appending (which on some Unix systems, means that all writes
append to the end of the file regardless of the current seek position).
In text mode, if encoding is not specified

In [41]:
m.flattten?

Object `m.flattten` not found.
